#!/bin/bash

configureSerialPort() {
	serialPort="$1"
	baudRate="$2"
	echo " config stty $baudRate  $serialPort"
	RS485_SETTINGS_1="1:0:18b2:0:3:1c:7f:15:4:5:1:0:11:13:1a:0:"
	RS485_SETTINGS_2="12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0"
	RS485_SETTINGS="$RS485_SETTINGS_1$RS485_SETTINGS_2"

	service ModemManager stop &>/dev/null
	setserial -av "$serialPort" closing_wait 3000 &>/dev/null

	stty -F "$serialPort" "$RS485_SETTINGS" &>/dev/null
	stty -F "$serialPort" "$RS485_SETTINGS"
	stty -F "$serialPort" "$baudRate" -crtscts
	if (( $? != 0 )); then
		echo "ERROR: cant configure serial port \"$serialPort\"" | tee "$tmpDirectory"/errorFile
		exit -1
	fi
}

echo "For break Ctrl+C"
#transmitt "$1" "$2"

baudRate="$1"
for port in /dev/ttyXR*; do

	echo "Transmitt data to $port , baudrate $1"
	configureSerialPort "$port" "$baudRate"
	dd if=/dev/urandom of="$port" bs=20000 count=10 &
	#dd if=/dev/urandom of="/dev/ttyXR29" bs=200 count=1 &

done